config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    # registrations: 'admins/registrations',
    sessions: 'admins/sessions',
    passwords: 'admins/passwords'
  }

  devise_for :customers, controllers: {
     registrations: 'public/registrations',
     sessions: 'public/sessions',
     passwords: 'public/passwords'
  }

  root 'public/homes#top'

  namespace :admins do
    get '/top' => 'homes#top'
    get 'search' => 'searchs#search', as: 'search'
  end

  namespace :admins do
    resources :customers, only: [:index, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      member do
        get :applicable_customer_index
      end
      collection do
        get :today_order_index
      end
    end
    resources :orders_datails,only: [:update]
  end

  scope module: :public do
    get '/about' => 'homes#about'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    post 'addresses/create2' => 'addresses#create2'
    post 'addresses/:address_id/create3' => 'addresses#create3', as: 'addresses_create3'
    get 'customers/my_page' => 'customers#show'
    get 'customer/edit' => 'customers#edit'
    patch 'customer' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :items, only: [:index, :show]
    get 'orders/new' => 'orders#new'
    post 'orders' => 'orders#create'
    get 'orders/thanks' => 'orders#thanks'
    get 'orders' => 'orders#index', as: 'orders_history'
    get 'orders/:id' => 'orders#show', as: 'orders_history_detail'
    post 'orders/confirm' => 'orders#confirm'
    resources :cart_items,only: [:index,:update,:create,:destroy] do
      collection do
        delete '/' => 'cart_items#all_destroy'
      end
    end
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :items, through: :cart_items
  has_many :orders
  has_many :addresses


  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :kana_first_name, presence: true
  validates :kana_last_name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true

  def self.search(content)
    Customer.where('last_name LIKE ?', "%#{content}%")
      .or(Customer.where('first_name LIKE ?', "%#{content}%"))
  end


  def active_for_authentication?
    super && (self.is_valid == false)
  end
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admins_customer_path(@customer), notice: "You have updated customer successfully."
    else
      render "edit"
    end
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :kana_first_name, :kana_last_name, :postal_code, :address, :phone_number, :email, :is_valid)
  end
  
  
  
  
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/views/admins/customers/edit.html.erb
<div class="row">
  <div class="col-xs-offset-1 col-xs-8">

    <h2 class="title_h2 text-center"><%= @customer.last_name + @customer.first_name %>さんの会員情報編集</h2>

      <% if @customer.errors.any? %>
        <%= @customer.errors.count %>件のエラーが発生しました
        <% @customer.errors.full_messages.each do |message| %>
        <%= message %>
        <% end %>
      <% end %>

    <div class="form-horizontal">
      <%= form_with model:@customer, url:admins_customer_path, local: true do |f| %>
        <div class="form-group">
          <%= f.label "会員ID", class: "col-sm-4 control-label" %>
          <div class="col-sm-8" >
          <%= f.label @customer.id %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label "氏名", class: "col-sm-4 control-label" %>
          <div class="col-sm-8" >
            <%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %>
            <%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "フリガナ", class: "col-sm-4 control-label" %>
          <div class="col-sm-8" >
            <%= f.text_field :kana_last_name, autofocus: true, autocomplete: "kana_last_name" %>
            <%= f.text_field :kana_first_name, autofocus: true, autocomplete: "kana_first_name" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "郵便番号", class: "col-sm-4 control-label" %>
          <div class="col-sm-8">
            <%= f.text_field :postal_code, autofocus: true, autocomplete: "postal_code" %>
          </div>
          </div>

        <div class="form-group">
          <%= f.label "住所", class: "col-sm-4 control-label" %>
          <div class="col-sm-8">
            <%= f.text_field :address, autofocus: true, autocomplete: "address" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "電話番号(ハイフンなし)", class: "col-sm-4 control-label"%>
          <div class="col-sm-8">
            <%= f.text_field :phone_number, autofocus: true, autocomplete: "phone_number" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label "メールアドレス", class: "col-sm-4 control-label" %>
          <div class="col-sm-8">
            <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
          </div>
        </div>

        <div class="form-check">
          <%= f.label "会員ステータス", class: "col-sm-4 control-label" %>
          <div class="col-sm-8">
            <%= f.radio_button :is_valid, :false, checked: true %>有効
            <%= f.radio_button :is_valid, :true %>退会済み
          </div>
        </div>
        <div class="actions">
          <%= f.submit "変更を保存する", class: "btn btn-info" %>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/admins/customers/index.html.erb
<div class="row">
  <div class="col-xs-offset-1 col-xs-8">

    <h1>会員一覧</h1>
		<table class="table">
			<thead>
				<tr>
		  		<th>会員ID</th>
					<th>氏名</th>
					<th>メールアドレス</th>
					<th>ステータス</th>
				</tr>
			</thead>

			<tbody>
				<% @customers.each do |customer| %>
					<tr>
						<td><%= customer.id %></td>
						<td><%= link_to customer.last_name + customer.first_name, admins_customer_path(customer) %></td>
						<td><%= customer.email %></td>
						<td>
							<% if customer.is_valid == false %>
								有効
							<% else %>
								退会済
							<% end %>
						</td>
					</tr>
				<% end %>
			</tbody>
			<div><%= paginate @customers %></div>
		</table>

  </div>
</div>

app/views/admins/customers/show.html.erb
<div class="row">
  <div class="col-xs-offset-1 col-xs-8">
    <h2><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h2>

    <table class="table table-bordered table-condensed" >
      <tbody>
        <tr>
          <td>顧客ID</td>
          <td>
            <%= @customer.id %>
            <% if @customer.is_valid == false %>
              <span  class="label label-primary">有効</span>
            <% else %>
              <span  class="label label-default">退会済み</span>
            <% end %>
          </td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= @customer.last_name + @customer.first_name %></td>
        </tr>
        <tr>
          <td>フリガナ</td>
          <td><%= @customer.kana_last_name + @customer.kana_first_name %></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%= @customer.postal_code %></td>
        <tr>
        <tr>
          <td>住所</td>
          <td><%= @customer.address %></td>
        <tr>
        <tr>
          <td>電話番号</td>
          <td><%= @customer.phone_number %></td>
        <tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= @customer.email %></td>
        <tr>
      </tbody>
    </table>

    <%= link_to "編集する", edit_admins_customer_path, class: "btn btn-info" %>
    <%= link_to "注文履歴一覧を見る", applicable_customer_index_admins_order_path,class: "btn btn-info" %>
  </div>
</div>