config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    # registrations: 'admins/registrations',
    sessions: 'admins/sessions',
    passwords: 'admins/passwords'
  }

  devise_for :customers, controllers: {
     registrations: 'public/registrations',
     sessions: 'public/sessions',
     passwords: 'public/passwords'
  }

  root 'public/homes#top'

  namespace :admins do
    get '/top' => 'homes#top'
    get 'search' => 'searchs#search', as: 'search'
  end

  namespace :admins do
    resources :customers, only: [:index, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      member do
        get :applicable_customer_index
      end
      collection do
        get :today_order_index
      end
    end
    resources :orders_datails,only: [:update]
  end

  scope module: :public do
    get '/about' => 'homes#about'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    post 'addresses/create2' => 'addresses#create2'
    post 'addresses/:address_id/create3' => 'addresses#create3', as: 'addresses_create3'
    get 'customers/my_page' => 'customers#show'
    get 'customer/edit' => 'customers#edit'
    patch 'customer' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :items, only: [:index, :show]
    get 'orders/new' => 'orders#new'
    post 'orders' => 'orders#create'
    get 'orders/thanks' => 'orders#thanks'
    get 'orders' => 'orders#index', as: 'orders_history'
    get 'orders/:id' => 'orders#show', as: 'orders_history_detail'
    post 'orders/confirm' => 'orders#confirm'
    resources :cart_items,only: [:index,:update,:create,:destroy] do
      collection do
        delete '/' => 'cart_items#all_destroy'
      end
    end
  end
end

app/controllers/admins/searchs_controller.rb
class Admins::SearchsController < ApplicationController
  def search
    @content = params[:content]
    @model = params[:model]
    if @model == "customer"
      @customers = Customer.search(@content)
    else
      @items = Item.search(@content)
    end
  end
end

app/helpers/admins/searchs_helper.rb
module Admins::SearchsHelper
end

app/views/admins/searchs/search.html.erb
<div class="row">
  <div class="col-xs-offset-1 col-xs-8">


		<% if @model == "customer" %>
		  <h2>Customers search for "<%= @content %>"</h2>
		  <table class="table">
				<thead>
					<tr>
						<th>name</th>
						<th>ステータス</th>
						<th></th>
						<th></th>
					</tr>
				</thead>

				<tbody>
					<% @customers.each do |customer| %>
					<tr>
						<td><%= customer.last_name %> <%= customer.first_name %></td>
						<td>
							<% if customer.is_valid == false %>
								有効
							<% else %>
								退会済
							<% end %>
						</td>
						<td><%= link_to "顧客詳細", admins_customer_path(customer) %></td>
						<td><%= link_to "顧客情報編集", edit_admins_customer_path(customer) %></td>
					</tr>
					<% end %>
				</tbody>
			</table>

		<% elsif @model == "item" %>
		  <h2>Items search for "<%= @content %>"</h2>
		  <table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th>Item</th>
						<th>税抜価格</th>
						<th></th>
						<th></th>
					</tr>
				</thead>

			  <tbody>
					<% @items.each do |item| %>
					<tr>
						<td><%= item.name %></td>
						<td><%= item.tax_out_price %>円</td>
						<td><%= link_to "アイテム詳細", item_path(item) %></td>
						<td><%= link_to "アイテム編集", edit_admins_item_path(item) %></td>
					</tr>
					<% end %>
			  </tbody>
		</table>
		<% else %>
		<% end %>

	</div>
</div>