config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    # registrations: 'admins/registrations',
    sessions: 'admins/sessions',
    passwords: 'admins/passwords'
  }

  devise_for :customers, controllers: {
     registrations: 'public/registrations',
     sessions: 'public/sessions',
     passwords: 'public/passwords'
  }

  root 'public/homes#top'

  namespace :admins do
    get '/top' => 'homes#top'
    get 'search' => 'searchs#search', as: 'search'
  end

  namespace :admins do
    resources :customers, only: [:index, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      member do
        get :applicable_customer_index
      end
      collection do
        get :today_order_index
      end
    end
    resources :orders_datails,only: [:update]
  end

  scope module: :public do
    get '/about' => 'homes#about'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    post 'addresses/create2' => 'addresses#create2'
    post 'addresses/:address_id/create3' => 'addresses#create3', as: 'addresses_create3'
    get 'customers/my_page' => 'customers#show'
    get 'customer/edit' => 'customers#edit'
    patch 'customer' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :items, only: [:index, :show]
    get 'orders/new' => 'orders#new'
    post 'orders' => 'orders#create'
    get 'orders/thanks' => 'orders#thanks'
    get 'orders' => 'orders#index', as: 'orders_history'
    get 'orders/:id' => 'orders#show', as: 'orders_history_detail'
    post 'orders/confirm' => 'orders#confirm'
    resources :cart_items,only: [:index,:update,:create,:destroy] do
      collection do
        delete '/' => 'cart_items#all_destroy'
      end
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :customer_id, :name, :address, presence: true
  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :customer, optional: true
    belongs_to :item, optional: true

    validates :customer_id, :item_id, :quantity, presence: true
	validates :quantity, numericality: { only_integer: true }



end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :items, through: :cart_items
  has_many :orders
  has_many :addresses


  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :kana_first_name, presence: true
  validates :kana_last_name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :email, presence: true

  def self.search(content)
    Customer.where('last_name LIKE ?', "%#{content}%")
      .or(Customer.where('first_name LIKE ?', "%#{content}%"))
  end


  def active_for_authentication?
    super && (self.is_valid == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
  validates :name, presence: true
  validates :is_valid, inclusion: {in: [true, false]}
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :customers, through: :cart_items
  has_many :cart_items
  has_many :order_details
  belongs_to :genre
  attachment :image
  validates :name, presence: true
  validates :image, presence: true
  validates :explanation, presence: true
  validates :tax_out_price, presence: true
  validates :explanation, presence: true
  
  def self.search(content)
    Item.where("name LIKE ?", "%#{content}%")
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy


  validates :postal_code, :address, :name, presence: true
  validates :postal_code,    length: { in: 7..7 }

	enum order_status: {"入金待ち": 0,"入金確認": 1,"製作中": 2,"発送待ち": 3, "発送済み": 4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  validates :item_id, :order_id, :quantity,:tax_in_price, presence: true
  validates :tax_in_price, :quantity, numericality: { only_integer: true }

  enum production_status: {"着手不可": 0,"製作待ち": 1,"製作中": 2,"製作完了": 3}
end

app/controllers/admins/homes_controller.rb
class Admins::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    now = Time.current
    @orders = Order.where(created_at: now.all_day).page(params[:page]).per(10)
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @item = Item.all
  end

  def new
    @item = Item.new
    @genre = Genre.all

  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admins_item_path(@item)
    else
      @genre = Genre.all
      render new_admins_item_path
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genre = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to admins_item_path(@item)
    else
      @genre = Genre.all
      render template: 'admins/items/edit'
    end
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :explanation, :tax_out_price, :image, :is_sale)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up, keys: [:last_name, :first_name, :kana_first_name, :kana_last_name, :postal_code, :address, :phone_number, :email]
      )
    devise_parameter_sanitizer.permit(
      :update, keys: [:last_name, :first_name, :kana_first_name, :kana_last_name, :postal_code, :address, :phone_number, :email]
      )
  end


  POSTAGE = 800

  # 0クレジットカード,1銀行振り込み
  PAYMENT_METHOD = ["クレジットカード","銀行振り込み"]

  TAX = 0.1



  private
    def after_sign_up_path_for(resource)
      items_path
    end

  # sign_in後のAdminとCustomerの遷移先の記述
  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admins_top_path
    when Customer
      items_path
    end
  end


  # sign_out後のAdminとCustomerの遷移先の記述
  def after_sign_out_path_for(resource)
    case resource
    when :admin, Admin
      new_admin_session_path
    when :customer, Customer
      new_customer_session_path
    else
      super
    end
  end

end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_datals_helper.rb
module Admins::OrdersDatalsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/admins/searchs_helper.rb
module Admins::SearchsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_cart
    @cart_items = current_customer.cart_items
  end

  # 税込の計算
  def tax_price(price)
    (price * 1.1).floor
  end

  # 小計の計算
  def sub_price(sub)
    (tax_price(sub.item.tax_out_price) * sub.quantity)
  end

  # 合計金額の計算
  def total_price(totals)
    price = 0
    totals.each do |total|
      price  +=  sub_price(total)
    end
    return price
  end

  # 請求額の計算
  def billing(order)
    total_price(current_cart) + order.postage
  end

  def full_name(customer)
    customer.last_name + customer.first_name
  end

  def full_address(customer)
    "#{customer.postal_code} #{customer.address}"
  end
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_flash.html.erb
<% if notice %>
	<div class="flash notice">
	  <span id="notice"><%= notice %></span>
	</div>
<% elsif flash[:success] %>
	<div class="flash success">
  	<span id="success"><%= flash[:success] %></span>
	</div>
<% elsif flash[:alert] %>
	<div class="flash danger">
	  <span id="alert"><%= flash[:alert] %></span>
	</div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top" >
  <div class="container">
    <nav class='nav navbar-nav navbar-left' style="padding-top:10px">
      <%= link_to "NAGANO CAKE", root_path, class: "logo" %>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if customer_signed_in? %>
          <li style="padding-top:15px">ようこそ、<%= current_customer.last_name %>さん！</li>
          <li><%= link_to 'マイページ', customers_my_page_path %></li>
          <li><%= link_to '商品一覧', items_path %></li>
          <li><%= link_to 'カート', cart_items_path %></li>
          <li><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete %></li>
        <% elsif admin_signed_in? %>
          <li><%= link_to '商品一覧', admins_items_path %></li>
          <li><%= link_to '会員一覧', admins_customers_path %></li>
          <li><%= link_to '注文履歴一覧', admins_orders_path %></li>
          <li><%= link_to 'ジャンル一覧', admins_genres_path %></li>
          <li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete %></li>
         <% else %>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to '商品一覧', items_path %></li>            
          <li><%= link_to '新規登録', new_customer_registration_path %></li>              
          <li><%= link_to 'ログイン', new_customer_session_path %></li>
         <% end %>
        </ul>
    </nav>
    <% if admin_signed_in? %>
      <div class="search-form pull-right" style="padding:15px 5px" >
        <%= form_with url: admins_search_path, method: :get, local:true do |f| %>
          <%= f.text_field :content %>
          <%= f.select :model, options_for_select({ "Customer" => "customer", "Item" => "item" }) %>
          <%= f.submit "検索" %>
        <% end %>
      </div>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('site-tile-150x150.png') %>
  </head>

  <body>

    <%= render "layouts/header" %>

    <div class="body">
      <div class="container">
        <div id="flash">
          <%= render "layouts/flash" %>
        </div>
        <%= yield %>
      </div>
    </div>

    <footer>
      <div class='container'>
  	    <div class='row'></div>
      </div>
    </footer>

  </body>
</html>