config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, controllers: {
    # registrations: 'admins/registrations',
    sessions: 'admins/sessions',
    passwords: 'admins/passwords'
  }

  devise_for :customers, controllers: {
     registrations: 'public/registrations',
     sessions: 'public/sessions',
     passwords: 'public/passwords'
  }

  root 'public/homes#top'

  namespace :admins do
    get '/top' => 'homes#top'
    get 'search' => 'searchs#search', as: 'search'
  end

  namespace :admins do
    resources :customers, only: [:index, :show, :edit, :update, :destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      member do
        get :applicable_customer_index
      end
      collection do
        get :today_order_index
      end
    end
    resources :orders_datails,only: [:update]
  end

  scope module: :public do
    get '/about' => 'homes#about'
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    post 'addresses/create2' => 'addresses#create2'
    post 'addresses/:address_id/create3' => 'addresses#create3', as: 'addresses_create3'
    get 'customers/my_page' => 'customers#show'
    get 'customer/edit' => 'customers#edit'
    patch 'customer' => 'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw'
    resources :items, only: [:index, :show]
    get 'orders/new' => 'orders#new'
    post 'orders' => 'orders#create'
    get 'orders/thanks' => 'orders#thanks'
    get 'orders' => 'orders#index', as: 'orders_history'
    get 'orders/:id' => 'orders#show', as: 'orders_history_detail'
    post 'orders/confirm' => 'orders#confirm'
    resources :cart_items,only: [:index,:update,:create,:destroy] do
      collection do
        delete '/' => 'cart_items#all_destroy'
      end
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy


  validates :postal_code, :address, :name, presence: true
  validates :postal_code,    length: { in: 7..7 }

	enum order_status: {"入金待ち": 0,"入金確認": 1,"製作中": 2,"発送待ち": 3, "発送済み": 4}
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
  	@orders = Order.all.page(params[:page]).per(10)
  end

  def applicable_customer_index
    @orders = Order.where(customer_id: params[:id]).page(params[:page]).per(10)
    render "index"
  end

  def today_order_index
    now = Time.current
    @orders = Order.where(created_at: now.all_day).page(params[:page]).per(10)
    render "index"
  end

	def show
		@PAYMENT_METHOD = PAYMENT_METHOD
		@order = Order.find(params[:id])
		@order_details = @order.order_details
	end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    # 注文ステータスが入金確認だったら、製作ステータスを製作待ちに変更
    if order_params[:order_status] == "入金確認"
			@order.order_details.each do |order_detail|
				order_detail.update(production_status: "製作待ち")
			end
			flash[:success] = "注文ステータスを変更しました。製作ステータスを製作待ちに変更しました。"
			redirect_to admins_order_path(@order)
		else
			flash[:success] = "注文ステータスを変更しました"
			redirect_to admins_order_path(@order)
    end
  end

	private
	def order_params
		  params.require(:order).permit(:order_status)
	end

end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/views/admins/orders/index.html.erb
<h2 class="title_h2 text-center">注文履歴一覧</h2>
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<table class="table table-bordered">
		  <thead>
		    <tr class="info">
		      <th class="col-xs-3">購入日時</th>
	      	  <th>購入者</th>
		      <th class="col-xs-1">注文個数</th>
		      <th class="col-xs-2">注文ステータス</th>
		    </tr>
		  </thead>

		  <tbody>
		    <% @orders.each do |order| %>
		      <tr>
		        <td>
		          <%= link_to admins_order_path(order)  do %>
		          	<%= order.created_at %>
		          <% end %>
		        </td>
		        <td class="text-left">
		          <%= full_name(order.customer) %>
		        </td>
		        <td class="text-right">
		          <%= order.order_details.count %>
		        </td>
    	        <td>
    	      	  <%= order.order_status %>
     	        </td>
     	      </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
    <div class="text-center"><%= paginate(@orders) %></div>
</div>

app/views/admins/orders/show.html.erb
<h2 class="title_h2 text-center">注文履歴詳細</h2>
  <div class="row">
    <div class="col-xs-12" >
      <div class="col-xs-9">
  		<div class="field">
  		  <div class="col-xs-4">
  			購入者
  		  </div>
  		  <div class="col-xs-8">
  		    <%= @order.name %>
  		  </div>
  		</div>

	    <div class="field">
	      <div class="col-xs-4">
	        配送先
	      </div>
	      <div class="col-xs-8">
	        <%= full_address(@order) %>
	      </div>
	    </div>

	    <div class="field">
	      <div class="col-xs-4">
	        支払い方法
	      </div>
	      <div class="col-xs-8">
	        <%= @PAYMENT_METHOD[@order.payment_method] %>
	      </div>
	    </div>

 	  <%= form_for(@order, url: admins_order_path, method: :patch) do |f| %>
 	    <div class="col-xs-4">注文ステータス</div>
      	  <div class="col-xs-6">
            <%= f.select :order_status, Order.order_statuses.keys, class: "order_status" %>
          </div>

      	<div class="actions">
          <div class="col-xs-2"><%= f.submit '更新'  ,class: "btn btn-primary" %></div>
      	</div>
      <% end %>
      </div>

	  <div class="col-xs-9">
			<table class="table table-bordered">
			    <thead>
			        <tr class="info">
			          <th class="col-xs-4">商品名</th>
			          <th>単価（税込）</th>
			          <th>数量</th>
			          <th>小計</th>
			          <th>製作ステータス</th>

			        </tr>
			    </thead>
				<tbody>
				<% if flash[:notice] %>
        	<div class="flash">
            <%= flash[:notice] %>
        	</div>
        <% end %>
				<% @order_details.each do |order_detail| %>
					<tr>
            <td class="text-left">
              <%= order_detail.item.name %>
            </td>
            <td class="text-right">
              ¥<%= tax_price(order_detail.item.tax_out_price).to_s(:delimited) %>
            </td>
            <td class="text-right">
              <%= order_detail.quantity %>
            </td>
            <td class="text-right">
              ¥<%= sub_price(order_detail).to_s(:delimited) %>
            </td>
            <td>
            <%= form_for(order_detail, url: admins_orders_datail_path(order_detail)) do |f| %>
            	<%= f.select :production_status, OrderDetail.production_statuses.keys, class: "order_status" %>
            	<%= f.submit '更新'  ,class: "btn btn-warning" %>
          　<% end %>
          　</td>
          </tr>
				<% end %>
				</tbody>
			</table>
	  </div>

	  <div class="col-xs-3">
			<table class="table table-bordered">
				<tr>
          <th class="info">商品合計</th>
					<td>¥<%= total_price(@order_details).to_s(:delimited) %></td>
				</tr>
				<tr>
					<th class="info">送料</th>
					<td>¥<%= @order.postage.to_s(:delimited) %></td>
				</tr>
				<tr>
					<th class="info">請求金額合計</th>
					<td>¥<%= @order.total_price.to_s(:delimited) %></td>
				</tr>
		    </table>
	  </div>
    <div class="col-xs-12">
      <%= link_to "戻る", admins_orders_path, class: "btn btn-info" %>
    </div>
	  </div>
  </div>